sudo: false
language: php
php:
  - 5.5
branches:
  except:
    - /^(\d+\.)+\d+$/
before_script:
  - curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
script:
  # Code Style
  - php phpcs.phar --standard=./phpcs.xml --encoding=utf-8 --report-width=180 ./app
notifications:
  email:
    recipients: [ lee@openmage.org ]
    on_success: always
    on_failure: always
